### ISSUE TITLE
sonarr_youtubedl: RoosterTeeth.com support?

### ISSUE THREAD

**Issue by jaredcat** [whatdaybob/Custom_Docker_Images#28]
I know youtube-dl supports `roosterteeth.com` to some degree but when I tried giving it `https://roosterteeth.com/series/red-vs-blue` for `Red Vs. Blue` it gaves an error (which seems to stop it from working on any other shows altogether).  
Wondering if there's any way to get this to work with rooster teeth shows. Not all their shows are on YouTube and this would also be great for First Members

**Comment by whatdaybob** [comment]
Hi @jaredkotoff , this is a limitation on the youtube-dl side, unfortunately playlist/series support was removed when the new API was used. I would suggest raising this directly with that project.
